
CREATE TABLE civilizations(
    id                   INTEGER  NOT NULL PRIMARY KEY 
   ,name                 VARCHAR(10) NOT NULL
   ,expansion            VARCHAR(17) NOT NULL
   ,army_type            VARCHAR(30) NOT NULL
   ,team_bonus           VARCHAR(93) NOT NULL
   ,civilization_bonus_0 VARCHAR(118) NOT NULL
   ,civilization_bonus_1 VARCHAR(109) NOT NULL
   ,civilization_bonus_2 VARCHAR(98)
   ,civilization_bonus_3 VARCHAR(78)
   ,civilization_bonus_4 VARCHAR(48)
 );
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (1,'Aztecs','The Conquerors','Infantry and Monk','Relics generate +33% gold','Villagers carry +5','Military units created 15% faster','+5 Monk hit points for each Monastery technology','Loom free',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (2,'Britons','Age of Kings','Foot Archer','Archery Ranges work 20% faster','Town Centers cost -50% wood upon reaching the Castle Age','Foot archers (excluding Skirmishers) have +1 range in Castle Age and +1 in Imperial Age (for +2 total)','Shepherds work 25% faster',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (3,'Byzantines','Age of Kings','Defensive','Monks +50% heal speed','Buildings (except gates) have +10% HP in Dark Age / +20% HP in Feudal Age  / +30% in Castle Age / +40% in Imperial Age','Spearman skirmisher and camel lines cost 25% less','Fire Ships attack 20% faster','Imperial Age costs -33%','Town Watch is free');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (4,'Celts','Age of Kings','Infantry','Siege Workshops work 20% faster','Infantry moves 15% faster','Lumberjacks work 15% faster','Siege weapons reload 20% faster','Sheep cannot be stolen if within one Celt unit''s line of sight',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (5,'Chinese','Age of Kings','Archer','Farms provide +45 food','Start game with 3 extra villagers but -50 wood and -200 food','Technologies cost -10% in Feudal Age/ -15% in Castle Age/-20% in Imperial Age','Town Centers support 10 population instead of 5','Demolition Ships have +50% HP',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (6,'Franks','Age of Kings','Cavalry','Knights have +2 line of sight','Castles are 25% cheaper','Knights have +20% HP','Farm upgrades are free (Mill is required to receive bonus)',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (7,'Goths','Age of Kings','Infantry','Barracks operate 20% faster','Infantry cost 35% less (starting in Feudal Age)','Infantry have +1 attack against buildings','Villagers have +5 attack versus wild boar','Hunters carry +15 meat','+10 to population limit in Imperial Age');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (8,'Huns','The Conquerors','Cavalry','Stables are 20% faster','Houses are not required to support population','Start game with -100 Wood','Cavalry Archers cost -25% in Castle Age/ -30% in Imperial Age','Trebuchets are 35% more accurate.',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (9,'Japanese','Age of Kings','Infantry','Galleys have +50% line of sight','Fishing Ships have 2x HP and +2 pierce armor','Fishing Ships work +5% faster in Dark Age/ +10% in Feudal Age/ +15% in Castle Age/ +20% in Imperial Age','Lumber Camps / Mining Camps / Mills are 50% cheaper','Infantry attack 25% faster (starting in Feudal Age)',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (10,'Koreans','The Conquerors','Tower and naval','Mangonel line has +1 range','Villagers have +3 line of sight','Stone miners work 20% faster','Guard Tower and Keep upgrades are free','Towers (except bombard towers) have +1 range in Castle Age/ +2 in Imperial Age',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (11,'Mayans','The Conquerors','Archer','Walls are 50% cheaper','Start game with 1 extra villager but -50 food','Natural resources last 20% longer','Archers cost -10% in Feudal Age/ -20% in Castle Age/ -30% in Imperial Age',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (12,'Mongols','Age of Kings','Cavalry Archer','Scout line has +2 Line of sight','Cavalry Archers reload 20% faster','Light Cavalry and Hussars have +30% HP','Hunters work 50% faster',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (13,'Persians','Age of Kings','Cavalry','Knights have +2 attack versus Archers','Start game with +50 wood and food','Town Center and Docks have 2x HP','Town Centers and Docks operate +10% faster in Feudal Age/ +15% in Castle Age/ +20% in Imperial Age',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (14,'Saracens','Age of Kings','Camel and naval','Foot archers have +2 attack bonus against buildings','Market trade cost is only 5%','Transport Ships have 2x HP and carry capacity','Galleys attack 20% faster','Cavalry Archers have +4 attack bonus against buildings',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (15,'Spanish','The Conquerors','Gunpowder and Monk','Trade units generate +33% Gold','Villagers construct buildings 30% faster','Blacksmith upgrades do not cost any gold','Cannon Galleons benefit from Ballistics (less reload time and more accuracy)','Hand Cannoneers and Bombard Cannons reload 15% faster',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (16,'Teutons','Age of Kings','Infantry','Units are more resistant to conversion','Monks have 2x healing range','Towers can garrison 2x units (more arrows)','Murder Holes is free','Farms cost 33% less','Town Centers have +1 attack and +5 line of sight');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (17,'Turks','Age of Kings','Gunpowder','Gunpowder units are created 20% faster','Gunpowder Units have +25% HP','Gunpowder technologies cost 50% less','Chemistry is free','Gold miners work 15% faster','Light Cavalry and Hussar upgrades are free');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (18,'Vikings','Age of Kings','Infantry and naval','Docks are 25% cheaper','Warships cost 20% less','Infantry have +10% HP in Feudal Age/ +15% in Castle Age/ +20% in Imperial Age','Wheelbarrow and Hand Cart are free',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (19,'Berbers','African Kingdoms','Calvary and Naval','Genitour availible at Archery Range','Villagers move +10% faster','Stable units cost -20% (starting in Castle Age)','Ships move +10% faster',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (20,'Burmese','Rise of Rajas','Monk and Elephant','Relics are visible on the min map','Free lumber camp upgrades','Infantry +1 Attacks per Age (starting in Feudal Age)','Monastery techs 50% cheaper',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (21,'Ethiopians','African Kingdoms','Archer','Towers and Outposts +3 LOS','Archers move +15% faster','Receive +100 gold and +100 food when advancing to the next age','Pikemen and Halberdier upgrades free"',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (22,'Goths','Age of Kings','Infantry','Barracks operate 20% faster','Infantry cost 35% less (starting in Feudal Age)','Infantry have +1 attack against buildings','Villagers have +5 attack versus wild boar','Hunters carry +15 meat','+10 to population limit in Imperial Age');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (23,'Incas','Forgotten Empires','Infantry','Farms built 50% faster','Start with a free llama','Villagers affected by Blacksmith upgrades','Houses support 10 population','Buildings cost -15% stone','Scout Cavalry is replaced by Eagle Warrior');
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (24,'Indians','Forgotten Empires','Gunpowder and Cavalry','Camels have +5 attack vs. buildings','Villagers cost -10% Dark, -15% Feudal, -20% Castle, -25% Imperial','Fishermen work 15% faster and carry +15','Camels +1/+1 armor',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (25,'Italians','Forgotten Empires','Archer and naval','Condottiero also available in allies'' barracks in Imperial Age (once you have built a castle)','Advance to next age costs -15%','All dock tech costs -50%','Fishing ship cost -15 wood','Gunpowder unit costs -25%',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (26,'Japanese','Age of Kings','Infantry','Galleys have +50% line of sight','Fishing Ships have 2x HP and +2 pierce armor','Fishing Ships work +5% faster in Dark Age/ +10% in Feudal Age/ +15% in Castle Age/ +20% in Imperial Age','Lumber Camps / Mining Camps / Mills are 50% cheaper','Infantry attack 25% faster (starting in Feudal Age)',NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (27,'Khmer','Rise of Rajas','Siege and Elephant Civilzation','Scorpions have +1 range','Prereq buildings aren''t required to advance to further ages or unlock other buildings','Battle Elephants are +15% faster','Villagers can garrison in Houses',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (28,'Magyars','Forgotten Empires','Calvary Infantry','Foot archers +2 LOS','Villagers can kill wolves with 1 strike','Forging, Iron Casting, Blast Furnace are free','Scout Cavalry, Light Cavalry, Hussar cost -15%',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (29,'Malians','African Kingdoms','Infantry','University researches +80% faster','Buildings cost -15% wood','Barracks unit +1 pierce armor per age','Gold mining upgrades free',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (30,'Portuguese','African Kingdoms','Naval and Gunpowder','Free cartography from Dark Age','All units costs -15% gold','Ships +10% HP','Can build Feitoria in Imperial Age',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (31,'Slavs','Forgotten Empires','Cavalry','Military buildings provide +5% population','Farmers works 15% faster','Siege weapons 15% cheaper','Tracking free',NULL,NULL);
 INSERT INTO civilizations(id,name,expansion,army_type,team_bonus,civilization_bonus_0,civilization_bonus_1,civilization_bonus_2,civilization_bonus_3,civilization_bonus_4) VALUES (32,'Vietnamese','Rise of Rajas','Archer','Have access to Imperial Skirmisher Upgrade','Reveals enemy positions at game start','Archery Range units have +10% HP in Feudal Age, +15% in Castle Age, and +20% in Imperial Age. Does not stack.',NULL,NULL,NULL);
